name: Autograder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-hidden-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install local package so hidden tests can import examples
          python -m pip install -e .
      - name: Run hidden autograder tests
        run: |
          python -m pytest -q grading/hidden_tests
